/// Yes. This is different from oauth
/// This scope handles the JWT generated by the service
/// because the openID foundation is annoying and 
/// doesn't want me to store the identification tokens
/// in the client (((((
